export const scoringConfig = {
  weights: {
    industryFit: 20,
    companySizeFit: 15,
    revenueFit: 15,
    growthSignals: 15,
    technologyFit: 10,
    locationFit: 10,
    contactCompleteness: 10,
    dataQuality: 5,
  },
  neutralPointsFraction: 0.4,
  tiers: {
    highPriorityMinimum: 80,
    mediumPriorityMinimum: 60,
  },
  industry: {
    preferredIndustries: [
      "healthcare technology",
      "data & analytics",
      "cloud infrastructure",
      "industrial automation",
      "financial services",
      "education technology",
      "cybersecurity",
      "logistics",
      "renewable energy",
      "manufacturing",
      "fleet technology",
      "enterprise software",
      "agriculture technology",
      "real estate technology",
      "telecommunications",
      "climate technology",
    ],
    preferredSubIndustries: [
      "business intelligence",
      "clinical operations",
      "developer platforms",
      "grid management",
      "identity management",
      "payments",
      "quality management",
      "robotics",
      "supply chain software",
    ],
    unmatchedIndustryPointsFraction: 0.2,
  },
  companySize: {
    preferredMinimum: 100,
    preferredMaximum: 5000,
    adjacentMinimum: 50,
    adjacentPointsFraction: 0.6,
    distantPointsFraction: 0.25,
  },
  revenue: {
    targetCurrency: "USD",
    preferredMinimum: 10_000_000,
    preferredMaximum: 500_000_000,
    adjacentMinimum: 1_000_000,
    adjacentPointsFraction: 0.65,
    distantPointsFraction: 0.3,
  },
  growth: {
    weights: {
      hiring: 6,
      growth: 5,
      funding: 4,
    },
    strongHiringRoles: 10,
    moderateHiringRoles: 3,
    moderateHiringPointsFraction: 0.75,
    lowHiringPointsFraction: 0.5,
    uncountedHiringPointsFraction: 0.75,
    neutralSignalTerms: [
      "no funding",
      "no hiring",
      "no recent growth",
      "not disclosed",
      "not reported",
      "unknown",
    ],
    negativeSignalTerms: [
      "layoff",
      "layoffs",
      "downsizing",
      "hiring freeze",
      "restructuring",
      "declining",
      "contraction",
      "closed locations",
    ],
    positiveGrowthTerms: [
      "growth",
      "growing",
      "expansion",
      "expanding",
      "new market",
      "increasing adoption",
      "product launch",
      "new region",
    ],
    positiveFundingTerms: [
      "seed",
      "series a",
      "series b",
      "series c",
      "series d",
      "growth round",
      "funding",
      "raised",
    ],
  },
  technology: {
    preferredTechnologies: [
      "aws",
      "azure",
      "google cloud",
      "snowflake",
      "databricks",
      "kubernetes",
      "salesforce",
      "hubspot",
      "postgresql",
      "okta",
      "workday",
      "tableau",
      "power bi",
      "dbt",
      "segment",
    ],
    strongMatchCount: 2,
    partialMatchPointsFraction: 0.7,
    unmatchedTechnologyPointsFraction: 0.2,
  },
  location: {
    preferredCountries: ["US", "CA", "GB", "IE", "DE", "FR", "NL", "SE", "CH"],
    otherCountryPointsFraction: 0.6,
  },
  contact: {
    missingFieldPointsFraction: 0.5,
    fields: [
      { field: "contactName", label: "name", points: 2 },
      { field: "contactTitle", label: "job title", points: 2 },
      { field: "contactEmail", label: "email", points: 2 },
      { field: "contactPhone", label: "phone", points: 2 },
      { field: "linkedinUrl", label: "LinkedIn profile", points: 2 },
    ],
  },
  dataQuality: {
    signals: {
      domain: 1,
      website: 0.75,
      dataSource: 0.75,
      lastUpdated: 1,
      verifiedEmail: 1,
      verifiedPhone: 0.5,
    },
    missingEvidencePointsFraction: 0.5,
  },
} as const;

export const scoringFactorMaximums = {
  industryFit: scoringConfig.weights.industryFit,
  companySizeFit: scoringConfig.weights.companySizeFit,
  revenueFit: scoringConfig.weights.revenueFit,
  growthSignals: scoringConfig.weights.growthSignals,
  technologyFit: scoringConfig.weights.technologyFit,
  locationFit: scoringConfig.weights.locationFit,
  contactCompleteness: scoringConfig.weights.contactCompleteness,
  dataQuality: scoringConfig.weights.dataQuality,
} as const;

export const MAX_OPPORTUNITY_SCORE = Object.values(
  scoringConfig.weights,
).reduce((sum, weight) => sum + weight, 0);
